apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
  resources:
    limits:
      memory: 20Mi
    requests:
      memory: 5Mi