apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
   - name: web-server
     image: quay.io/ocsci/nginx:latest
     volumeMounts:
       - name: mypvc
         mountPath: /mnt/
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: test-pavan4
       readOnly: false
