apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 110Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/pavangovindraj/mnt/data"

